### ISSUE TITLE
Feature 5: Multiple Clinics

### ISSUE THREAD

**Issue by MikeSmvl** [Oumar96/Mercedes#33]
- [x] Make an administrator page and account

- [x] Admin panel

- [x] Add a new clinic

- [x] Add people to existing clinics

Clinics have unique names and hold an **array** of nurses, physicians and patients.
