### ISSUE TITLE
SAD Table of contents

### ISSUE THREAD

**Issue by Oumar96** [Oumar96/Mercedes#7]
Table of contents

- [x] **1. Introduction** @c-cha16 

    - [x] Purpose   

    - [x] Scope 

   

    - [x] Definitions, acronyms, and abbreviations   

- [x] **2. Architectural representation** @MikeSmvl  @SMHK341 

- [x] **3. Architectural requirements: goals and constraints** @svenaci @Songtone 

    - [x] 3.1 Functional requirements (Use case view)

    - [x] 3.2 Non-functional requirements

- [x] **4. Use case view (Scenarios)**  @CogNoman @TDDEL 

- [x] **5. Logical view** @Calbers4 @Oumar96 @c-cha16 

    - [x] **5.1 Layers, tiers etc.**  

    - [x] **5.2 Subsystems**

    - [x] **5.3 Use case realizations**    

- [x] **6. Development (Implementation) view** @MikeSmvl @SMHK341 

    - [ ] 6.1 Reuse of components and frameworks

- [x] **7. Process view** @Calbers4 @Oumar96 

- [x] **8. Deployment (Physical) view** @MikeSmvl @SMHK341 

- [x] **9. Data view (optional)**

- [x] **10. Quality** @Songtone @svenaci 

- [x] **11. Design patterns**
